import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function contact() {
	return (
		<>
			<Head>
				<title>AAA</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, viewport-fit=cover"
				/>
				<meta name="format-detection" content="telephone=no" />
			</Head>
			<Header />
			<main className="contact">
				{/* <h2>Contact</h2>
				<form>
					<label>
						Participe :
						<input
							name="isGoing"
							type="checkbox"
							checked={this.state.isGoing}
							onChange={this.handleInputChange}
						/>
					</label>
					<br />
					<label>
						Nombre d'invités :
						<input
							name="numberOfGuests"
							type="number"
							value={this.state.numberOfGuests}
							onChange={this.handleInputChange}
						/>
					</label>
				</form> */}
			</main>
		</>
	);
}
