import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Form from "@/components/Form";

export default function contact() {
  return (
    <>
      <Head>
        <title>AAA</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
        <meta name="format-detection" content="telephone=no" />
      </Head>
      <Header />
      <main>
        <div className="contact-container">
          <h2>Contact</h2>
          <Form />
        </div>
      </main>
      <Footer />
    </>
  );
}
