import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function creations() {
  return (
    <>
      <Head>
        <title>AAA</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
        <meta name="format-detection" content="telephone=no" />
      </Head>
      <Header />
      <main>
        <div className="creations-banner">
          <h1>A venir prochainement...</h1>
        </div>
      </main>
    </>
  );
}
