import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect, useRef } from "react";
import useColorTheme from "@/hooks/useColorTheme";
import classNames from "@/hooks/classNames";

export default function Home() {
	const { isLight } = useColorTheme();

	const ref = useRef(null);

	const handleClick = () => {
		ref.current?.scrollIntoView({ behavior: "smooth" });
	};

	useEffect(() => {
		AOS.init();
	}, []);

	return (
		<>
			<Head>
				<title>AAA</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, viewport-fit=cover"
				/>
				<meta name="format-detection" content="telephone=no" />
			</Head>
			<Header />
			<main>
				<div className="wrap">
					<section
						className={classNames(
							"hero-banner",
							isLight ? "hero-banner-light" : ""
						)}
					>
						<div className="hero-banner-texte">
							<h1
								className="slogan"
								data-aos="fade-right"
								data-aos-once="true"
								data-aos-duration="800"
							>
								{/* Ambition <span className="slogan-gradient">And</span> Adaptation. */}
								<span
									className={classNames(
										"slogan-gradient",
										isLight ? "slogan-gradient-light" : ""
									)}
								>
									A
								</span>
								mbition{" "}
								<span
									className={classNames(
										"slogan-gradient",
										isLight ? "slogan-gradient-light" : ""
									)}
								>
									A
								</span>
								nd{" "}
								<span
									className={classNames(
										"slogan-gradient",
										isLight ? "slogan-gradient-light" : ""
									)}
								>
									A
								</span>
								daptation
								<span
									className={classNames(
										"slogan-gradient",
										isLight ? "slogan-gradient-light" : ""
									)}
								>
									.
								</span>
							</h1>
							<h3
								className="slogan-sous-texte"
								data-aos="fade-right"
								data-aos-once="true"
								data-aos-delay="100"
								data-aos-duration="800"
							>
								Laissez votre empreinte sur le Web avec{" "}
								<span
									className={classNames(
										"slogan-gradient",
										isLight ? "slogan-gradient-light" : ""
									)}
								>
									Arion.
								</span>
							</h3>
						</div>
						<img
							src="hero.png"
							alt="dessin appareil web"
							className={classNames(
								"hero-banner-image",
								isLight ? "hero-banner-image-light" : ""
							)}
						/>
						<img
							src={"fleche" + (isLight ? "light" : "") + ".svg"}
							alt=""
							className="fleche"
							onClick={handleClick}
						/>
						<img
							src={"wave" + (isLight ? "-light1" : "") + ".svg"}
							alt=""
							className="wave"
						/>
					</section>
				</div>
				<div className="line"></div>
				<span ref={ref}></span>
				<div className="wrap">
					<section
						className="presentation"
						data-aos="fade-right"
						data-aos-once="true"
						data-aos-duration="700"
						data-aos-anchor-placement="top-center"
					>
						<h2>Qui sommes nous ?</h2>
						<p className={isLight ? "presentation-light" : ""}>
							Nous sommes 3 futurs ingénieurs de l'ESIEA qui avons
							décidé d'accompagner les entreprises voulant booster
							leurs ventes. De la création de sites web au
							référencement en ligne, nous proposons de nombreux
							services sur-mesure. Avec nous, la seule limite est
							votre imagination.
						</p>
						{/* <img
						src="Frame.svg"
						alt=""
						className="presentation-image"
					/> */}
					</section>
				</div>

				<div className="wrap">
					<section className="nos-services-banner">
						<h2 className="service-titre">Nos Services</h2>
						<div className="nos-services-grid">
							<div
								className={classNames(
									"service-item",
									isLight ? "service-item-light" : ""
								)}
								data-aos="flip-right"
								data-aos-anchor-placement="top-center"
								data-aos-once="true"
								data-aos-duration="500"
							>
								<img
									src={
										"test3" +
										(isLight ? "light" : "") +
										".svg"
									}
									alt=""
								/>
								<h3>Creation de site web</h3>
								<p>
									Takimata dolore eos sea labore. Volutpat
									sanctus vero et sea et accusam ipsum. Est
									facilisis kasd et at est sed est sanctus in
									sit
								</p>
							</div>
							<div
								className={classNames(
									"service-item",
									isLight ? "service-item-light" : ""
								)}
								data-aos="flip-right"
								data-aos-anchor-placement="top-center"
								data-aos-once="true"
								data-aos-delay="100"
								data-aos-duration="500"
							>
								<img
									src={
										"test4" +
										(isLight ? "light" : "") +
										".svg"
									}
									alt=""
								/>
								<h3>SEO</h3>
								<p>
									Takimata dolore eos sea labore. Volutpat
									sanctus vero et sea et accusam ipsum. Est
									facilisis kasd et at est sed est sanctus in
									sit
								</p>
							</div>
						</div>
						<button
							className={classNames(
								"ensavoirplus-button",
								isLight ? "ensavoirplus-button-light" : ""
							)}
						>
							En savoir plus
						</button>
					</section>
				</div>

				<div className="wrap">
					<section className="nos-realisations-banner">
						<h2 className="nos-realisations-titre">
							Nos Réalisations
						</h2>
						<div
							className="nos-realisations-item"
							data-aos="fade-right"
							data-aos-duration="700"
							data-aos-anchor-placement="top-center"
							data-aos-once="true"
						>
							<img src="MyDonut.png" alt="" />
							<div className="item-overlay">
								<div className="overlay-texte">
									<h3>M.D</h3>
									<p>My Donut</p>
								</div>
							</div>
						</div>
					</section>
				</div>
			</main>
			<Footer />
		</>
	);
}
