import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect, useRef } from "react";
import useColorTheme from "@/hooks/useColorTheme";
import classNames from "@/hooks/classNames";
import Image from "next/image";
import HeroImage from "@/public/hero.png";
import Fleche from "@/public/fleche.svg";
import BorderImage from "@/public/border.svg";
import Test3 from "@/public/test3.svg";
import Test4 from "@/public/test4.svg";
import BorderBottomImage from "@/public/borderbottom.svg";
import MyDonutImage from "@/public/MyDonut.png";

export default function Home() {
  const { isLight } = useColorTheme();

  const ref = useRef(null);

  const handleClick = () => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    AOS.init();
  }, []);

  return (
    <>
      <Head>
        <title>AAA</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
        <meta name="format-detection" content="telephone=no" />
      </Head>
      <Header />
      <main>
        <section
          className={classNames(
            "hero-banner",
            isLight ? "hero-banner-light" : ""
          )}
        >
          <div className="hero-banner-texte">
            <h1 className="slogan">
              {/* Ambition <span className="slogan-gradient">And</span> Adaptation. */}
              <span
                className={classNames(
                  "slogan-gradient",
                  isLight ? "slogan-gradient-light" : ""
                )}
              >
                A
              </span>
              mbition{" "}
              <span
                className={classNames(
                  "slogan-gradient",
                  isLight ? "slogan-gradient-light" : ""
                )}
              >
                A
              </span>
              nd{" "}
              <span
                className={classNames(
                  "slogan-gradient",
                  isLight ? "slogan-gradient-light" : ""
                )}
              >
                A
              </span>
              daptation
              <span
                className={classNames(
                  "slogan-gradient",
                  isLight ? "slogan-gradient-light" : ""
                )}
              >
                .
              </span>
            </h1>
            <h3
              className="slogan-sous-texte"
              data-aos="fade-right"
              data-aos-once="true"
              data-aos-delay="100"
              data-aos-duration="800"
            >
              Laissez votre empreinte sur le Web avec{" "}
              <span
                className={classNames(
                  "slogan-gradient",
                  isLight ? "slogan-gradient-light" : ""
                )}
              >
                Arion.
              </span>
            </h3>
          </div>
          <Image
            src={HeroImage}
            alt="dessin appareil web"
            className={classNames(
              "hero-banner-image",
              isLight ? "hero-banner-image-light" : ""
            )}
            priority="true"
          />
          <Image src={Fleche} alt="" className="fleche" onClick={handleClick} />
          <img
            src={"wave" + (isLight ? "-light1" : "") + ".svg"}
            alt=""
            className="wave"
            priority="true"
          />
        </section>
        <span ref={ref}></span>
        <section
          className="presentation"
          data-aos="fade-right"
          data-aos-once="true"
          data-aos-duration="700"
          data-aos-anchor-placement="top-center"
        >
          <h2>Qui sommes nous ?</h2>
          <p>
            Nous sommes 3 futurs ingénieurs de l'ESIEA qui avons décidé
            d'accompagner les entreprises voulant booster leurs ventes. De la
            création de sites web au référencement en ligne, nous proposons de
            nombreux services sur-mesure. Avec nous, la seule limite est votre
            imagination.
          </p>
        </section>
        <section className="nos-services-banner nos-services-banner-light">
          {/* Faire le changement de theme */}
          <h2 className="service-titre">Nos Services</h2>
          <div className="nos-services-grid">
            <div
              className="service-item"
              data-aos="flip-right"
              data-aos-anchor-placement="top-center"
              data-aos-once="true"
              data-aos-duration="500"
            >
              <Image src={Test3} alt="" />
              <h3>Creation de site web</h3>
              <p>
                Takimata dolore eos sea labore. Volutpat sanctus vero et sea et
                accusam ipsum. Est facilisis kasd et at est sed est sanctus in
                sit
              </p>
            </div>
            <div
              className="service-item"
              data-aos="flip-right"
              data-aos-anchor-placement="top-center"
              data-aos-once="true"
              data-aos-delay="100"
              data-aos-duration="500"
            >
              <Image src={Test4} alt="" />
              <h3>SEO</h3>
              <p>
                Takimata dolore eos sea labore. Volutpat sanctus vero et sea et
                accusam ipsum. Est facilisis kasd et at est sed est sanctus in
                sit
              </p>
            </div>
          </div>
          <button className="ensavoirplus-button">En savoir plus</button>
        </section>
        <section className="nos-realisations-banner nos-realisations-banner-light">
          {/* Faire le changement de theme */}
          <h2 className="nos-realisations-titre">Nos Réalisations</h2>
          <div
            className="nos-realisations-item"
            data-aos="fade-right"
            data-aos-duration="700"
            data-aos-anchor-placement="top-center"
            data-aos-once="true"
          >
            <Image src={MyDonutImage} alt="" />
            <div className="item-overlay">
              <div className="overlay-texte">
                <h3>M.D</h3>
                <p>My Donut</p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
