import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect, useRef } from "react";
// import { useLocation } from "react-router-dom";
// import { useRouter } from "next/router";
// useRouter;

export default function offers(props) {
  // const location = useLocation();
  // console.log(props, " props");
  // console.log(location, " useLocation Hook");
  // const data = location.state?.data;

  return (
    <>
      <Head>
        <title>AAA</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
        <meta name="format-detection" content="telephone=no" />
      </Head>
      <Header />
      <main className="offers">
        <h2>Pourquoi nous choisir ?</h2>
        <div className="atout">
          <div className="atout-item">
            <img src="" alt="" />
            <h2>1.</h2>
            <h3>Design</h3>
            <p>
              Profitez d'un design fidèle à vos ambitions et qui attirera
              l'attention de vos visiteurs.
            </p>
          </div>
          <div className="atout-item">
            <img src="" alt="" />
            <h2>2.</h2>
            <h3>Responsive</h3>
            <p>Votre site web est adapté à tous les écrans.</p>
          </div>
          <div className="atout-item">
            <h2>3.</h2>
            <img src="" alt="" />
            <h3>Accessible</h3>
            <p>
              Nos sites sont conformes aux normes AAA d'accessibilté. Vous
              pouvez aussi profiter d'un thème sombre et d'un thème clair.
            </p>
          </div>
        </div>
        <h2>Nos offres</h2>
        <div className="nos-offres-grid">
          <div className="nos-offres-item">
            <h3>Site Vitrine</h3>
            <p>
              Une véritable carte de visite de votre entreprise. Mettez en
              valeur votre savoir-faire.
            </p>
            <div className="nos-offres-item-line"></div>
            <button>Obtenir un devis</button>
          </div>
        </div>
      </main>
    </>
  );
}
